/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    kotlin("jvm") version "1.3.71"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Kotlin
    implementation(kotlin("stdlib-jdk8"))
    implementation("org.jetbrains.kotlinx", "kotlinx-coroutines-core", "1.3.7")
    implementation("org.jetbrains.kotlinx", "kotlinx-coroutines-reactor", "1.3.7")

    // JDA
    implementation("net.dv8tion", "JDA", "4.1.1_165") {
        exclude(module = "opus-java")
    }
    implementation("club.minnced", "jda-reactor", "1.1.0")
    implementation("dev.augu.nino", "Butterfly","0.1.1")

    // Testing tools
    testImplementation("junit", "junit", "4.12")
    testImplementation("io.kotest", "kotest-runner-junit5-jvm", "4.1.0.RC2")
    testImplementation("io.kotest", "kotest-assertions-core-jvm", "4.1.0.RC2")
    testImplementation("io.kotest", "kotest-property-jvm", "4.1.0.RC2")
    testImplementation("io.mockk", "mockk", "1.10.0")
    testImplementation("org.jetbrains.kotlinx", "kotlinx-coroutines-test", "1.3.7")

    // Logging
    api("org.slf4j", "slf4j-api", "1.6.1")
    testImplementation("org.slf4j", "slf4j-simple", "1.6.1")
}

application {
    // Define the main class for the application.
    mainClassName = "dev.augu.nino.AppKt"
}
