/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.augu.nino

import io.kotest.core.spec.style.DescribeSpec
import io.kotest.matchers.nulls.shouldNotBeNull

class AppTest : DescribeSpec({
    describe("AppTests "){
        val classUnderTest = App()
        it("shoud have greeting") {
            classUnderTest.greeting.shouldNotBeNull()
        }
    }
})
